### ISSUE TITLE
export to csv fails when BIMI flag is included

### ISSUE THREAD

**Issue by EmailKarma** [domainaware/checkdmarc#126]
I believe part of this is related to the "fields" list in __init__.py missing the [BIMI values] for the CSV output. I looked but couldn't figure out where the missing values originate from to attempt to make adjustments. 

> checkdmarc --skip-tls example.com -b default -n 9.9.9.9 -o c:\temp\example.csv

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python312\Scripts\checkdmarc.exe\__main__.py", line 7, in <module>
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python312\Lib\site-packages\checkdmarc\_cli.py", line 122, in _main
    output_to_file(path, results_to_csv(results))
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python312\Lib\site-packages\checkdmarc\__init__.py", line 388, in results_to_csv
    rows = results_to_csv_rows(results)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python312\Lib\site-packages\checkdmarc\__init__.py", line 273, in results_to_csv_rows
    row["bimi_warnings"] = "|".join(_bimi["warnings"])
                                    ~~~~~^^^^^^^^^^^^
KeyError: 'warnings'

**Comment by EmailKarma** [comment]
I realize it would be helpful to mention I'm running v 5.3.1
