### ISSUE TITLE
5.7.9: CSV output errors due to bimi

### ISSUE THREAD

**Issue by EmailKarma** [domainaware/checkdmarc#153]
Running into this error, when trying to create a CSV related to BIMI with a short file of domains. 

checkdmarc source.txt -o output.csv
Traceback (most recent call last):
  File "/home/user/.local/bin/checkdmarc", line 8, in <module>
    sys.exit(_main())
  File "/home/user/.local/lib/python3.10/site-packages/checkdmarc/_cli.py", line 159, in _main
    output_to_file(path, results_to_csv(results))
  File "/home/user/.local/lib/python3.10/site-packages/checkdmarc/__init__.py", line 435, in results_to_csv
    rows = results_to_csv_rows(results)
  File "/home/user/.local/lib/python3.10/site-packages/checkdmarc/__init__.py", line 289, in results_to_csv_rows
    row["bimi_warnings"] = "|".join(_bimi["warnings"])
KeyError: 'warnings'

**Comment by seanthegeek** [comment]
Do you know which domain is causing this error? BIMI warnings convert correctly when I check cardinalhealth.com with checkdmark 5.7.9.

**Comment by zerocool303a** [comment]
i get the same error by the domain inkcal.de
