### ISSUE TITLE
Error parsing rua and ruf when exporting to CSV

### ISSUE THREAD

**Issue by dmuse89** [domainaware/checkdmarc#76]
Using python3.9.12, I am running into this error on some domains when exporting to a CSV format.  This error does not present itself when exporting to JSON on the exact same domain.

example: `checkdmarc aboutyou.de -f csv`

```
Traceback (most recent call last):
  File "~/envs/checkdmarc/bin/checkdmarc", line 8, in <module>
    sys.exit(_main())
  File "~/envs/checkdmarc/lib/python3.9/site-packages/checkdmarc.py", line 2627, in _main
    results = results_to_csv(results)
  File "~/envs/checkdmarc/lib/python3.9/site-packages/checkdmarc.py", line 2534, in results_to_csv
    rows = results_to_csv_rows(results)
  File "~/envs/checkdmarc/lib/python3.9/site-packages/checkdmarc.py", line 2500, in results_to_csv_rows
    addresses = list(map(lambda u: u["scheme"] + ":" +
  File "~/envs/checkdmarc/lib/python3.9/site-packages/checkdmarc.py", line 2500, in <lambda>
    addresses = list(map(lambda u: u["scheme"] + ":" +
TypeError: string indices must be integers
```

**Comment by tchenChemo** [comment]
I have the same issue too checkdmarc c:\domainlist.csv -f csv -o c:\output.csv. throwing the same error

**Comment by seanthegeek** [comment]
Turns out this was fix a while back.
