### ISSUE TITLE
exception thrown on broken SPF record

### ISSUE THREAD

**Issue by kjellchr** [domainaware/checkdmarc#8]
```
$ checkdmarc helsekonferansen.no
Traceback (most recent call last):
  File "/usr/local/bin/checkdmarc", line 9, in <module>
    load_entry_point('checkdmarc==1.0.1', 'console_scripts', 'checkdmarc')()
  File "/usr/local/lib/python3.4/dist-packages/checkdmarc.py", line 667, in _main
    nameservers=args.nameserver)
  File "/usr/local/lib/python3.4/dist-packages/checkdmarc.py", line 622, in check_domains
    nameservers=nameservers)
  File "/usr/local/lib/python3.4/dist-packages/checkdmarc.py", line 496, in parse_spf_record
    result = spf_qualifiers[match[0]]
KeyError: '1'
```

record:
```
$ dig +short helsekonferansen.no TXT
"v=spf1" "include:spf.protection.outlook.com" "-all"
```

**Comment by seanthegeek** [comment]
The concatenation specified by the SPF RFC https://tools.ietf.org/html/rfc7208#section-3.3

Means that

> "v=spf1" "include:spf.protection.outlook.com" "-all"

Becomes

> v=spf1include:spf.protection.outlook.com-all

I added an additional check after SPF concatenation to account for this. 

That domain now returns an invalid SPF record error.
